#TODO: FIX ALL CONSTANTS
swerve_drive_controller:
    type:       talon_swerve_drive_controller/TalonSwerveDriveController
    
    speed: ['speed_joint_fl', 'speed_joint_fr', 'speed_joint_bl', 'speed_joint_br']
    steering: ['steering_joint_fl', 'steering_joint_fr', 'steering_joint_bl', 'steering_joint_br']
    publish_rate: 25
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # fix me
    wheel_radius: 0.0381 # m
    max_speed: 3.6 #3.628571429
    max_accel: 2.0 #2
    max_brake_accel: 2.5 #4
    ang_accel_conv: 1.0 #0.741176471
    
    f_s: 0.12
    f_a: 0.005 #use torque curve instead? TODO: FIX
    f_v: 0.00315528

    #TODO: FIX BELOW!!!!	
    f_s_s: 0.05
    f_s_v: 0.07
   
    #consider adding stuff for the steering wheels too 
    mass: 70
    motor_free_speed: 5840
    motor_stall_torque: 1.4
    motor_quantity: 4
    file_name: "offsets.txt"
    invert_wheel_angle: False
    ratio_encoder_to_rotations: 0.618792651
    ratio_motor_to_rotations: 0.202380952364087  
    ratio_motor_to_steering: 49
    encoder_drive_get_V_units: 1 
    encoder_drive_set_V_units: 1 
    encoder_drive_get_P_units: 1 
    encoder_drive_set_P_units: 1
    encoder_steering_get_units: 1
    encoder_steering_set_units: 1
    wheel_coords1x: -0.28575
    wheel_coords1y: 0.28575   
    wheel_coords2x: 0.28575
    wheel_coords2y: 0.28575 
    wheel_coords3x: -0.28575
    wheel_coords3y: -0.28575   
    wheel_coords4x: 0.28575
    wheel_coords4y: -0.28575   
 
    cmd_vel_timeout: 0.5 # we test this separately, give plenty for the other tests
    speed_joint_fl:
        joint: fl_drive #fix pid
        close_loop_values:
            - {p: 0.1, i: 0.0006, d: 1, f: 0.06145, i_zone: 500}
            - {p: 0.2, i: 0.002, d: 0.1, f: 0.06145, i_zone: 700}
        sensor_phase: True
        invert_output: True
        feedback_type: CTRE_MagEncoder_Relative
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
    speed_joint_fr:
        joint: fr_drive #fix pid
        close_loop_values:
            - {p: 0.1, i: 0.0006, d: 1, f: 0.06145, i_zone: 500}
            - {p: 0.2, i: 0.002, d: 0.1, f: 0.06145, i_zone: 700}
        sensor_phase: True
        invert_output: True
        feedback_type: CTRE_MagEncoder_Relative
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
    speed_joint_bl:
        joint: bl_drive #fix pid
        close_loop_values: 
            - {p: 0.1, i: 0.0006, d: 1, f: 0.06145, i_zone: 500}
            - {p: 0.2, i: 0.002, d: 0.1, f: 0.06145, i_zone: 700}
        sensor_phase: True
        invert_output: True
        feedback_type: CTRE_MagEncoder_Relative
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
    speed_joint_br:
        joint: br_drive #fix pid
        close_loop_values:
            - {p: 0.1, i: 0.0006, d: 1, f: 0.06145, i_zone: 500}
            - {p: 0.2, i: 0.002, d: 0.1, f: 0.06145, i_zone: 700}
        sensor_phase: True
        invert_output: True
        feedback_type: CTRE_MagEncoder_Relative
        voltage_compensation_enable: True
        current_limit_continuous_amps: 20
        current_limit_enable: True
    steering_joint_fl:
        joint: fl_angle
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 4.2, i: 0.006, d: 45.0, f: 0.47, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 5.0, i: 0.03, d: 75.0, f: 0.47, i_zone: 1200} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
        invert_output: true
        sensor_phase: true
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 32
        motion_acceleration: 150
        
        voltage_compensation_enable: true
    steering_joint_fr:
        joint: fr_angle
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 4.2, i: 0.006, d: 45.0, f: 0.47, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 5.0, i: 0.03, d: 75.0, f: 0.47, i_zone: 1200} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
       
        invert_output: true
        sensor_phase: true
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 32
        motion_acceleration: 150
        voltage_compensation_enable: true
    steering_joint_br:
        joint: br_angle
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 4.2, i: 0.006, d: 45.0, f: 0.47, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 5.0, i: 0.03, d: 75.0, f: 0.47, i_zone: 1200} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
        
        invert_output: true
        sensor_phase: true
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 32
        motion_acceleration: 150
        voltage_compensation_enable: true
    steering_joint_bl:
        joint: bl_angle
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 4.2, i: 0.006, d: 45.0, f: 0.47, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 5.0, i: 0.03, d: 75.0, f: 0.47, i_zone: 1200} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
        invert_output: true
        sensor_phase: true
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 32
        motion_acceleration: 150
        voltage_compensation_enable: true
