elevator_controller:
    type:  elevator_controller/ElevatorController
    lift: ["lift_joint", "lift_follower1_joint", "lift_follower2_joint"]
    intake1: "intake1_joint"
    intake2: "intake2_joint"
    pivot: "pivot_joint"
    
    intake_power_diff_multiplier: .85
    arm_length: 0.466729 
    max_extension: 2.1 #3.628571429 #29619 
    climb_height: 2.0 
    min_extension: 0.38 
   

    custom_f_lift_high: 153.45 #Fix  
    custom_f_lift_low: 53.45   #Fix  

    custom_f_arm_mass: 153.45 #Fix  
    custom_f_arm_fric: 53.45   #Fix  

    after_shift_max_accel: 2 #fix
    after_shift_max_vel: .5 #fix


    hook_depth: 0.314706  #FIX
    hook_min_height: 1.27 #FIX
    hook_max_height: 1.45 #FIX
   #Fix below remove poly points 
    polygon_points: [-1.0, .93, -1.0, 3.0, 0.1, 3.0, 0.1, .93, 0.75, .93, 0.75, -1.0, -1.0, -1.0, -1.0, .93] #~5 cm of clearance   
    cut_off_line: .93 
    lift_joint:
        joint: lift
        close_loop_values:
            - {p: .4, i: 0.0005, d: 0.2, f: 0.1669, i_zone: 750} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: .5, i: 0.0005, d: 7.5, f: 0.0235389351901052, i_zone: 750} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500} 
        invert_output: True
        sensor_phase: True
        feedback_type: CTRE_MagEncoder_Absolute
        conversion_factor: 0.0454676
        motion_cruise_velocity: 2 
        motion_acceleration: 4
        current_limit_continuous_amps: 60
        current_limit_enable: True

    lift_follower1_joint:
        joint: lift_follower1 
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    lift_follower2_joint:
        joint: lift_follower2
        invert_output: True
        current_limit_continuous_amps: 60
        current_limit_enable: True
    pivot_joint:
        type: talon_controllers/TalonMotionMagicCloseLoopController
        joint: pivot
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 1, i: 0.0002, d: 2.0, f: .6, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
            - {p: 1, i: 0.0002, d: 2.0, f: .6, i_zone: 500} #{p: 7.15, i: 0.006, d: 90.0, f: 0.609381981, i_zone: 500}
        invert_output: True
        sensor_phase: False
        peak_output_forward: 0.4
        peak_output_reverse: -0.4
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 1
        motion_acceleration: 2
        voltage_compensation_enable: true
        softlimit_forward_threshold: 0
        softlimit_forward_threshold: 1
        conversion_factor: 1 #FIX
        current_limit_continuous_amps: 30
        current_limit_enable: True

    intake1_joint:
        joint: intake1
        invert_output: True
        sensor_phase: False
        current_limit_continuous_amps: 40
        current_limit_enable: True
    intake2_joint:
        joint: intake2
        invert_output: False
        sensor_phase: True
        current_limit_continuous_amps: 40
        current_limit_enable: True
