# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - {name: base_to_lf_angle, type: can_talon_srx, can_id: 1}
      - {name: lf_angle_to_speed, type: can_talon_srx, can_id: 1}
      - {name: base_to_rf_angle, type: can_talon_srx, can_id: 1}
      - {name: rf_angle_to_speed, type: can_talon_srx, can_id: 1}
      - {name: base_to_lr_angle, type: can_talon_srx, can_id: 1}
      - {name: lr_angle_to_speed, type: can_talon_srx, can_id: 1}
      - {name: base_to_rr_angle, type: can_talon_srx, can_id: 1}
      - {name: rr_angle_to_speed, type: can_talon_srx, can_id: 1}
   sim_control_mode: 1 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

swerve_base_controller:
    type: "SWBC/SteeredWheelBaseController"
    linear_speed_limit: 3.5
    linear_acceleration_limit: 7
    linear_decelration_limit: 7

    yaw_speed_limit: 6.3
    yaw_acceleration_limit: 12
    yaw_decelration_limit: 12

    wheels:
        - {steering_joint: base_to_lf_angle, axle_joint: lf_angle_to_speed, diameter: .1524}
        - {steering_joint: base_to_rf_angle, axle_joint: rf_angle_to_speed, diameter: .1524}
        - {steering_joint: base_to_rr_angle, axle_joint: rr_angle_to_speed, diameter: .1524}
        - {steering_joint: base_to_lr_angle, axle_joint: lr_angle_to_speed, diameter: .1524}
