auto_params:
    modes:
        -
            - [
                #Test Profile
                [{ x: [-7.669172, 18.985068, -12.473896, 0.208, -0.048724, 2.998724], y: [6.6748125, -12.3895624, 3.35475, 0.2, 4.0599375, 0.5000625], orient: [5.46964485452, -13.2608268541, 8.47024536045, -0.482093663912, 1.30303030303, 0.0], time: 4.0 },
                 { x: [0.0375, -1.4375, 6.9925, -12.7225, 10.57, -1.44], y: [2.944, -20.207, 52.122, -61.889, 31.86, -2.43], orient: [0.0824631575483, -0.563358534344, 1.40275640002, -1.59261973137, 0.872584525107, 1.29817418303], time: 3.0 },
                 { x: [-2.1025, 26.3925, -129.7875, 311.2375, -363.27, 167.84], y: [-5.083, 61.597, -294.495, 696.677, -818.568, 385.098], orient: [-27.5841921627, 344.70496621, -1700.01761395, 4133.8222341, -4958.99635285, 2351.77937071], time: 4.0 }]
                ]

                #Straight line back and forth 0 1 0
            - [
                [{x: [-0.281172, 0.716068, -0.679896, 0.325, -0.068724, 2.998724], y: [23.2398125, -54.0295625, 31.44975, 0.58, 1.2299375, 0.5000625], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], time: 4.0 },
                { x: [-0.5575, 3.3825, -7.8025, 8.4575, -4.25, 3.78], y: [-4.945, 38.185, -114.245, 166.225, -120.91, 38.66], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], time: 4.0 }],
                
                #straight line rotate 180 0 1 1
                [{x: [-0.281172, 0.716068, -0.679896, 0.325, -0.068724, 2.998724], y: [23.2398125, -54.0295625, 31.44975, 0.58, 1.2299375, 0.5000625], orient: [18.1495161065, -45.2268917536, 29.7591932068, 0.41573397881, 0.0240384615385, 0.02], time: 4.0 },
                { x: [-0.5575, 3.3825, -7.8025, 8.4575, -4.25, 3.78], y: [-4.945, 38.185, -114.245, 166.225, -120.91, 38.66], orient: [0.0420340330463, -0.331622180445, 1.02099143857, -1.50210618611, 1.03065617058, 2.88163672436], time: 4.0 }],
               ]
                #4 cube RRR start on right 0 2 0
            - [
                [{ x: [-5.077172, 13.509068, -10.835896, 1.86, -0.228724, 2.998724], y: [29.3998125, -72.1495625, 46.18975, -0.15, 3.5199375, 0.5000625], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [0.713, -6.046, 19.101, -28.522, 19.994, -3.014], y: [-6.2595, 46.3035, -132.1355, 180.7005, -118.721, 37.422], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [2.068, -24.892, 120.475, -292.862, 355.538, -169.558], y: [1.7225, -22.0445, 112.2285, -283.6915, 355.055, -169.33], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [2.004, -32.422, 204.843, -628.274, 929.234, -524.392], y: [0.1425, -3.7165, 33.6465, -139.5655, 272.489, -197.68], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [-1.9155, 44.343, -408.4855, 1870.708, -4257.734, 3854.52], y: [-11.766, 265.2895, -2382.234, 10647.8645, -23687.343, 20987.888], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [11.1215, -305.938, 3357.1075, -18367.287, 50102.616, -54511.48], y: [4.8965, -135.643, 1498.5245, -8251.763, 22647.982, -24780.362], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [-1.915, 62.39, -811.545, 5268.45, -17070.63, 22089.14], y: [-10.535, 343.05, -4459.185, 28921.36, -93591.5, 120898.57], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }]
                ]
                #single scale 0 3 0 start middle scale left
            - [
                [{ x: [-0.36, -1.005, 2.04, 3.705, -7.74, 0.48], y: [9.475, -22.76, 13.395, 1.7, 2.13, 0.3], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [1.18, -9.475, 29.34, -42.775, 29.5, -10.65], y: [10.035, -74.94, 215.015, -295.68, 197.95, -48.14], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }],

                #single scale 0 3 1 start left scale right
                [{ x: [2.57, -7.135, 6.89, -0.325, -1.01, -2.94], y: [8.665, -18.115, 7.335, -0.155, 7.89, 0.49], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [6.06, -43.415, 117.54, -149.495, 93.05, -25.69], y: [-1.755, 11.015, -25.905, 28.985, -15.09, 8.86], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }],

                #Test Profile 0 3 2
                [{ x: [-7.669172, 18.985068, -12.473896, 0.208, -0.048724, 2.998724], y: [6.6748125, -12.3895624, 3.35475, 0.2, 4.0599375, 0.5000625], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [0.0375, -1.4375, 6.9925, -12.7225, 10.57, -1.44], y: [2.944, -20.207, 52.122, -61.889, 31.86, -2.43], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 { x: [-2.1025, 26.3925, -129.7875, 311.2375, -363.27, 167.84], y: [-5.083, 61.597, -294.495, 696.677, -818.568, 385.098], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }]
                ]

        #- { times: [9.0, 0.0, 0.0], x: [[-7.669172, 18.985068, -12.473896, 0.208, -0.048724, 2.998724], [0.0375, -1.4375, 6.9925, -12.7225, 10.57, -1.44], [-2.1025, 26.3925, -129.7875, 311.2375, -363.27, 167.84]], y: [[6.6748125, -12.3895624, 3.35475, 0.2, 4.0599375, 0.5000625], [2.944, -20.207, 52.122, -61.889, 31.86, -2.43], [-5.083, 61.597, -294.495, 696.677, -818.568, 385.098]], orient: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]} #mode 0 layout 3 pos 2
             #   [{ x: [0.373828, -1.123932, 0.355104, -0.325, -0.038724, 2.998724], y: [22.1698125, -55.3245625, 36.50975, 0.445, 1.3499375, 0.5000625], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
              #   { x: [-17.075, 125.54, -354.415, 478.49, -312.77, 82.47], y: [-4.465, 56.995, -285.515, 699.055, -834.02, 393.83], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
               #  { x: [6.34, -77.29, 373.89, -896.62, 1065.37, -503.81], y: [0.66, -13.46, 105.93, -403.13, 743.59, -526.87], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                # { x: [-13.19, 234.71, -1661.0, 5842.49, -10213.61, 7096.96], y: [-9.8, 220.16, -1970.11, 8776.23, -19459.29, 17185.77], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [-3.03, 68.81, -622.65, 2806.29, -6299.21, 5630.72], y: [3.325, -91.105, 996.615, -5441.145, 14826.96, -16126.73], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [-0.165, 5.095, -62.425, 378.915, -1137.96, 1349.47], y: [-43.255, 1404.205, -18198.355, 117694.155, -379849.32, 489457.99], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [12.935, -419.675, 5435.975, -35137.965, 113350.68, -145992.77], y: [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }]
                #]
            
            #- { times: [9.0, 0.0, 0.0], x: [[0.373828, -1.123932, 0.355104], [-0.325, -0.038724, 2.998724],[-17.075, 125.54, -354.415, 478.49, -312.77, 82.47], [6.34, -77.29, 373.89, -896.62, 1065.37, -503.81],[-13.19, 234.71, -1661, 5842.49, -10213.61, 7096.96], [-3.03, 68.81, -622.65, 2806.29, -6299.21, 5630.72], [-0.165, 5.095, -62.425, 378.915, -1137.96, 1349.47], [12.935, -419.675, 5435.975, -35137.965, 113350.68, -145992.77]],
            
            #y: [[22.1698125, -55.3245625, 36.50975, 0.445, 1.3499375, 0.5000625], [-4.465, 56.995, -285.515, 699.055, -834.02, 393.83], [0.66, -13.46, 105.93, -403.13, 743.59, -526.87], [-9.8, 220.16, -1970.11, 8776.23, -19459.29, 17185.77], [3.325, -91.105, 996.615, -5441.145, 14826.96, -16126.73], [-43.255, 1404.205, -18198.355, 117694.155, -379849.32, 489457.99], [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6]], orient: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 1, pos 1
#above is for s:r ll





            #- [
             #   [{ x: [1.393828, -4.178932, 3.715104, -0.21, -1.078724, 2.998724], y: [14.0648125, -34.2895625, 21.85475, -0.01, 2.4199375, 0.5000625], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
              #   { x: [0.875, -6.495, 18.335, -24.985, 16.47, 1.56], y: [-1.075, 8.01, -23.635, 34.06, -22.75, 9.93], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
               #  { x: [3.205, -40.375, 201.275, -495.905, 602.63, -286.2], y: [2.64, -33.86, 171.92, -431.59, 535.83, -258.03], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                # { x: [-19.225, 336.395, -2338.655, 8073.985, -13845.61, 9439.74], y: [-6.935, 118.915, -810.265, 2743.475, -4617.39, 3096.99], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [0.56, -12.685, 114.6, -515.795, 1156.07, 1034.18], y: [-10.23, 231.725, -2089.67, 9375.375, -20922.91, 18585.31], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [-1.075, 8.01, -23.635, 34.06, -22.75, 9.93], y: [7.85, -215.895, 2367.8, -12943.675, 35267.34, -38310.94], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [18.07, -586.17, 7590.92, -49055.33, 158202.34, -203699.09], y: [-54.795, 1779.055, -23058.575, 149135.075, -481326.36, 620185.58], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] },
                 #{ x: [9.18, -344.51, 5163.93, -38643.88, 144376.5, -215433.12], y: [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6], orient: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] }]
                #]

#            - { times: [9.0, 0.0, 0.0], x: [[1.393828, -4.178932, 3.715104, -0.21, -1.078724, 2.998724], [0.875, -6.495, 18.335, -24.985, 16.47, 1.56],[3.205, -40.375, 201.275, -495.905, 602.63, -286.2], [-19.225, 336.395, -2338.655, 8073.985, -13845.61, 9439.74],[0.56, -12.685, 114.6, -515.795, 1156.07, 1034.18], [-6.265, 172.45, -1893.765, 10370.68, -28320.68, 30852.07], [18.07, -586.17, 7590.92, -49055.33, 158202.34, -203699.09], [9.18, -344.51, 5163.93, -38643.88, 144376.5, -215433.12]], 

#y: [[14.0648125, -34.2895625, 21.85475, -0.01, 2.4199375, 0.5000625], [-1.075, 8.01, -23.635, 34.06, -22.75, 9.93],[2.64, -33.86, 171.92, -431.59, 535.83, -258.03], [-6.935, 118.915, -810.265, 2743.475, -4617.39, 3096.99],[-10.23, 231.725, -2089.67, 9375.375, -20922.91, 18585.31], [7.85, -215.895, 2367.8, -12943.675, 35267.34, -38310.94], [-54.795, 1779.055, -23058.575, 149135.075, -481326.36, 620185.58], [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 1, pos 1
#s:r rl
        - - - { x: [[-5.077172, 13.509068, -10.835896, 1.86, -0.228724, 2.998724], [0.713, -6.046, 19.101, -28.522, 19.994, -3.014], [2.068, -24.892, 120.475, -292.862, 355.538, -169.558],[2.004, -32.422, 204.843, -628.274, 929.234, -524.392], [-1.9155, 44.343, -408.4855, 1870.708, -4257.734, 3854.52], [11.1215, -305.938, 3357.1075, -18367.287, 50102.616, -54511.48], [-1.915, 62.39, -811.545, 5268.45, -17070.63, 22089.14]], y: [[29.3998125, -72.1495625, 46.18975, -0.15, 3.5199375, 0.5000625], [-6.2595, 46.3035, -132.1355, 180.7005, -118.721, 37.422], [1.7225, -22.0445, 112.2285, -283.6915, 355.055, -169.33],[0.1425, -3.7165, 33.6465, -139.5655, 272.489, -197.68], [-11.766, 265.2895, -2382.234, 10647.8645, -23687.343, 20987.888],[4.8965, -135.643, 1498.5245, -8251.763, 22647.982, -24780.362], [-10.535, 343.05, -4459.185, 28921.36, -93591.5, 120898.57]], orient: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]} #mode 0, layout 0, pos 0 TODO - IF TRY TO GO BACKWARD LAST ORIENT COEF SHOULD BE 0.0



        #-    #mode 0 layout 1 pos 1
        #-    #mode 0 layout 1 pos 2
        - { times: [9.0, 0.0, 0.0], x: [[-7.669172, 18.985068, -12.473896, 0.208, -0.048724, 2.998724], [0.0375, -1.4375, 6.9925, -12.7225, 10.57, -1.44], [-2.1025, 26.3925, -129.7875, 311.2375, -363.27, 167.84]], y: [[6.6748125, -12.3895624, 3.35475, 0.2, 4.0599375, 0.5000625], [2.944, -20.207, 52.122, -61.889, 31.86, -2.43], [-5.083, 61.597, -294.495, 696.677, -818.568, 385.098]], orient: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]} #mode 0 layout 3 pos 2



        #THIS IS THE TEST PROFILE
        #THIS IS THE TEST PROFILE
        #THIS IS THE TEST PROFILE
        #THIS IS THE TEST PROFILE

        - { times: [9.0, 0.0, 0.0], x: [[-7.669172, 18.985068, -12.473896, 0.208, -0.048724, 2.998724], [0.0375, -1.4375, 6.9925, -12.7225, 10.57, -1.44], [-2.1025, 26.3925, -129.7875, 311.2375, -363.27, 167.84]], y: [[6.6748125, -12.3895624, 3.35475, 0.2, 4.0599375, 0.5000625], [2.944, -20.207, 52.122, -61.889, 31.86, -2.43], [-5.083, 61.597, -294.495, 696.677, -818.568, 385.098]], orient: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]} #mode 0 layout 3 pos 2



# one dash changes layer 1, two dashes changes layer 2, three dashes change layer 3
       
        

        #- { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 0, layout 0, pos 0 #mode 0, layout 0, pos 1
          #- - { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 0, layout 1, pos 0

#            - { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 0, layout 1, pos 1
 #       - - - { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 0, pos 0
  #          - { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 0, pos 1
   #       - - { times: [9.0, 0.0, 0.0], x: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], y: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 1, pos 0


#            - { times: [9.0, 0.0, 0.0], x: [[1.393828, -4.178932, 3.715104, -0.21, -1.078724, 2.998724], [0.875, -6.495, 18.335, -24.985, 16.47, 1.56],[3.205, -40.375, 201.275, -495.905, 602.63, -286.2], [-19.225, 336.395, -2338.655, 8073.985, -13845.61, 9439.74],[0.56, -12.685, 114.6, -515.795, 1156.07, 1034.18], [-6.265, 172.45, -1893.765, 10370.68, -28320.68, 30852.07], [18.07, -586.17, 7590.92, -49055.33, 158202.34, -203699.09], [9.18, -344.51, 5163.93, -38643.88, 144376.5, -215433.12]], y: [[14.0648125, -34.2895625, 21.85475, -0.01, 2.4199375, 0.5000625], [-1.075, 8.01, -23.635, 34.06, -22.75, 9.93],[2.64, -33.86, 171.92, -431.59, 535.83, -258.03], [-6.935, 118.915, -810.265, 2743.475, -4617.39, 3096.99],[-10.23, 231.725, -2089.67, 9375.375, -20922.91, 18585.31], [7.85, -215.895, 2367.8, -12943.675, 35267.34, -38310.94], [-54.795, 1779.055, -23058.575, 149135.075, -481326.36, 620185.58], [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6]], orient: [[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 1, pos 1
#s:r rl




            #- { times: [9.0, 0.0, 0.0], x: [[0.373828, -1.123932, 0.355104], [-0.325, -0.038724, 2.998724],[-17.075, 125.54, -354.415, 478.49, -312.77, 82.47], [6.34, -77.29, 373.89, -896.62, 1065.37, -503.81],[-13.19, 234.71, -1661, 5842.49, -10213.61, 7096.96], [-3.03, 68.81, -622.65, 2806.29, -6299.21, 5630.72], [-0.165, 5.095, -62.425, 378.915, -1137.96, 1349.47], [12.935, -419.675, 5435.975, -35137.965, 113350.68, -145992.77]], y: [[22.1698125, -55.3245625, 36.50975, 0.445, 1.3499375, 0.5000625], [-4.465, 56.995, -285.515, 699.055, -834.02, 393.83], [0.66, -13.46, 105.93, -403.13, 743.59, -526.87], [-9.8, 220.16, -1970.11, 8776.23, -19459.29, 17185.77], [3.325, -91.105, 996.615, -5441.145, 14826.96, -16126.73], [-43.255, 1404.205, -18198.355, 117694.155, -379849.32, 489457.99], [-2.64, 102.6, -1590.73, 12296.45, -47383.34, 72805.6]], orient: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0],[0.0, 0.0, 0.0]]} #mode 1, layout 1, pos 1
#above is for s:r ll
#####################################################

        
  #switch-scale-scale-scale
  #mode_1_layout_1_2_pos_1_times: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  #mode_1_layout_1_2_pos_2_times:  
  #mode_1_layout_3_4_pos_1_times:  
  #mode_1_layout_3_4_pos_2_times:  
  #
  #longway scale-switch-scale
  #mode_2_layout_1_2_pos_1_times: DON'T EXIST
  #mode_2_layout_1_2_pos_2_times: DON'T EXIST
  #mode_2_layout_3_4_pos_1_times:
  #mode_2_layout_3_4_pos_2_times:
  #
  ##shortway scale-switch-scale
  #mode_3_layout_1_2_pos_1_times:  
  #mode_3_layout_1_2_pos_2_times:  
  #mode_3_layout_3_4_pos_1_times:  
  #mode_3_layout_3_4_pos_2_times:  
  #0 0 0
  #1 0 0
  #0 1 0
  #1 1 0
  ##longway scale-scale-scale
  #mode_4_layout_1_2_pos_1_times:  
  #mode_4_layout_1_2_pos_2_times:  
  #mode_4_layout_3_4_pos_1_times:  
  #mode_4_layout_3_4_pos_2_times:  
  #
  ##basic switch
  #mode_5_layout_1_2_pos_1_times:  #THESE WILL ALL HAVE THE SAME TIMES
  #mode_5_layout_1_2_pos_2_times:  #FIGURE SOMETHING OUT
  #mode_5_layout_3_4_pos_1_times:  
  #mode_5_layout_3_4_pos_2_times:  
  #
  ##longway switch
  #mode_5_layout_1_2_pos_1_times:  #THESE WILL ALL HAVE THE SAME TIMES
  #mode_5_layout_1_2_pos_2_times:  #FIGURE SOMETHING OUT
  #mode_5_layout_3_4_pos_1_times:  
  #mode_5_layout_3_4_pos_2_times:  
  #
  ##basic scale
  #mode_4_layout_1_2_pos_1_times:  #THESE WILL ALL HAVE THE SAME TIMES
  #mode_4_layout_1_2_pos_2_times:  #FIGURE SOMETHING OUT
  #mode_4_layout_3_4_pos_1_times:  
  #mode_4_layout_3_4_pos_2_times:  
  #
  ##longway scale
  #mode_4_layout_1_2_pos_1_times:  #THESE WILL ALL HAVE THE SAME TIMES
  #mode_4_layout_1_2_pos_2_times:  #FIGURE SOMETHING OUT
  #mode_4_layout_3_4_pos_1_times:  
  #mode_4_layout_3_4_pos_2_times:  
  #
  ##cross baseline
  #mode_4_layout_1_2_pos_1_times:  #THESE WILL ALL HAVE THE SAME TIMES
  #mode_4_layout_1_2_pos_2_times:  #FIGURE SOMETHING OUT
  #mode_4_layout_3_4_pos_1_times:  
  #mode_4_layout_3_4_pos_2_times:  
